//
// Generated file, do not edit! Created by nedtool 5.6 from veins/modules/application/traci/reportDump.msg.
//

#ifndef __VEINS_REPORTDUMP_M_H
#define __VEINS_REPORTDUMP_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif

// cplusplus {{
#include "veins/base/utils/Coord.h"
#include "veins/modules/messages/BaseFrame1609_4_m.h"
#include "veins/base/utils/SimpleAddress.h"
#include "veins/modules/application/traci/myClasses.h"
// }}


namespace veins {

/**
 * Class generated from <tt>veins/modules/application/traci/reportDump.msg:31</tt> by nedtool.
 * <pre>
 * packet infoMsg extends BaseFrame1609_4
 * {
 *     LAddress::L2Type senderAddress = -1;
 *     reportDumpClass dump;
 * }
 * </pre>
 */
class VEINS_API infoMsg : public ::veins::BaseFrame1609_4
{
  protected:
    LAddress::L2Type senderAddress;
    reportDumpClass dump;

  private:
    void copy(const infoMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const infoMsg&);

  public:
    infoMsg(const char *name=nullptr, short kind=0);
    infoMsg(const infoMsg& other);
    virtual ~infoMsg();
    infoMsg& operator=(const infoMsg& other);
    virtual infoMsg *dup() const override {return new infoMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual LAddress::L2Type& getSenderAddress();
    virtual const LAddress::L2Type& getSenderAddress() const {return const_cast<infoMsg*>(this)->getSenderAddress();}
    virtual void setSenderAddress(const LAddress::L2Type& senderAddress);
    virtual reportDumpClass& getDump();
    virtual const reportDumpClass& getDump() const {return const_cast<infoMsg*>(this)->getDump();}
    virtual void setDump(const reportDumpClass& dump);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const infoMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, infoMsg& obj) {obj.parsimUnpack(b);}

} // namespace veins

#endif // ifndef __VEINS_REPORTDUMP_M_H

