//
// Generated file, do not edit! Created by nedtool 5.6 from veins/modules/application/traci/reportMsg.msg.
//

#ifndef __VEINS_REPORTMSG_M_H
#define __VEINS_REPORTMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif

// cplusplus {{
#include "veins/base/utils/Coord.h"
#include "veins/modules/messages/BaseFrame1609_4_m.h"
#include "veins/base/utils/SimpleAddress.h"
// }}


namespace veins {

/**
 * Class generated from <tt>veins/modules/application/traci/reportMsg.msg:41</tt> by nedtool.
 * <pre>
 * packet reportMsg extends BaseFrame1609_4
 * {
 *     LAddress::L2Type reporterAddress = -1;
 *     LAddress::L2Type reporteeAddress = -1;
 *     int reportedMsgId;
 *     bool foundValid = true;
 * }
 * </pre>
 */
class VEINS_API reportMsg : public ::veins::BaseFrame1609_4
{
  protected:
    LAddress::L2Type reporterAddress;
    LAddress::L2Type reporteeAddress;
    int reportedMsgId;
    bool foundValid;

  private:
    void copy(const reportMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const reportMsg&);

  public:
    reportMsg(const char *name=nullptr, short kind=0);
    reportMsg(const reportMsg& other);
    virtual ~reportMsg();
    reportMsg& operator=(const reportMsg& other);
    virtual reportMsg *dup() const override {return new reportMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual LAddress::L2Type& getReporterAddress();
    virtual const LAddress::L2Type& getReporterAddress() const {return const_cast<reportMsg*>(this)->getReporterAddress();}
    virtual void setReporterAddress(const LAddress::L2Type& reporterAddress);
    virtual LAddress::L2Type& getReporteeAddress();
    virtual const LAddress::L2Type& getReporteeAddress() const {return const_cast<reportMsg*>(this)->getReporteeAddress();}
    virtual void setReporteeAddress(const LAddress::L2Type& reporteeAddress);
    virtual int getReportedMsgId() const;
    virtual void setReportedMsgId(int reportedMsgId);
    virtual bool getFoundValid() const;
    virtual void setFoundValid(bool foundValid);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const reportMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, reportMsg& obj) {obj.parsimUnpack(b);}

} // namespace veins

#endif // ifndef __VEINS_REPORTMSG_M_H

